FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn package

FROM openjdk:17 AS runtime

WORKDIR /app

COPY --from=build /app/target/demo-1.0-SNAPSHOT-jar-with-dependencies.jar /app/

ENV MAIN_CLASS=SuperPeer

ENTRYPOINT ["sh", "-c", "java -cp demo-1.0-SNAPSHOT-jar-with-dependencies.jar $MAIN_CLASS"]
